CREATE DATABASE "Filial_west"
   WITH ENCODING='UTF8'
   OWNER=postgres
   CONNECTION LIMIT=-1;

CREATE DATABASE "Filial_east"
   WITH ENCODING='UTF8'
   OWNER=postgres
   CONNECTION LIMIT=-1;

CREATE DATABASE "Filial_south"
   WITH ENCODING='UTF8'
   OWNER=postgres
   CONNECTION LIMIT=-1;

CREATE DATABASE "Warehouse"
   WITH ENCODING='UTF8'
   OWNER=postgres
   CONNECTION LIMIT=-1;

CREATE DATABASE "Showcase"
   WITH ENCODING='UTF8'
   OWNER=postgres
   CONNECTION LIMIT=-1;